
OrdererOrgs:
  - Name: Orderer
    Domain: org
    Specs:
      - Hostname: orderer
PeerOrgs:

  - Name: Org1
    Domain: org1.org
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.org
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org3
    Domain: org3.org
    Template:
      Count: 1
    Users:
      Count: 1
